"""create app_ideas table

Revision ID: d5e97c8a2ee2
Revises: 
Create Date: 2026-04-19 21:30:41.331585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5e97c8a2ee2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING_CSO_VETTING', 'PENDING_ANALYSIS', 'ANALYSIS_COMPLETE', 'APPROVED_FOR_DEV', 'PUBLISHED', name='ideastatus'), nullable=False),
    sa.Column('apk_path', sa.String(length=255), nullable=True),
    sa.Column('ai_generated_title', sa.String(length=255), nullable=True),
    sa.Column('ai_generated_summary', sa.Text(), nullable=True),
    sa.Column('competition_analysis', sa.Text(), nullable=True),
    sa.Column('swot_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_ideas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_ideas_source_url'), ['source_url'], unique=True)
        batch_op.create_index(batch_op.f('ix_app_ideas_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_ideas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_ideas_status'))
        batch_op.drop_index(batch_op.f('ix_app_ideas_source_url'))

    op.drop_table('app_ideas')
    # ### end Alembic commands ###
