"""Decoupled Flask and Celery architecture

Revision ID: f1c347d3dfad
Revises: 
Create Date: 2025-07-06 14:03:40.873032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1c347d3dfad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_ANALYSIS', 'ANALYSIS_COMPLETE', name='ideastatus'), nullable=False),
    sa.Column('ai_generated_title', sa.String(length=255), nullable=True),
    sa.Column('ai_generated_summary', sa.Text(), nullable=True),
    sa.Column('cmo_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_ideas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_ideas_source_url'), ['source_url'], unique=True)
        batch_op.create_index(batch_op.f('ix_app_ideas_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_ideas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_ideas_status'))
        batch_op.drop_index(batch_op.f('ix_app_ideas_source_url'))

    op.drop_table('app_ideas')
    # ### end Alembic commands ###
