"""feat: Add CSO/CPO models and workflow

Revision ID: 2c9a411e8b3e
Revises: 
Create Date: 2024-03-15 11:45:11.234567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c9a411e8b3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_ideas', sa.Column('status', sa.Enum('PENDING_CSO_VETTING', 'PENDING_CPO_ANALYSIS', 'PENDING_CEO_APPROVAL', 'REJECTED_BY_CEO', 'APPROVED_FOR_DEV', 'PENDING_CEO_TESTING', 'PUBLISHED', name='ideastatus'), nullable=True))
    op.add_column('app_ideas', sa.Column('ceo_feedback', sa.Text(), nullable=True))
    op.add_column('app_ideas', sa.Column('ai_generated_title', sa.String(length=255), nullable=True))
    op.add_column('app_ideas', sa.Column('ai_generated_summary', sa.Text(), nullable=True))
    op.add_column('app_ideas', sa.Column('competition_analysis', sa.Text(), nullable=True))
    op.add_column('app_ideas', sa.Column('swot_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_app_ideas_status'), 'app_ideas', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_ideas_status'), table_name='app_ideas')
    op.drop_column('app_ideas', 'swot_analysis')
    op.drop_column('app_ideas', 'competition_analysis')
    op.drop_column('app_ideas', 'ai_generated_summary')
    op.drop_column('app_ideas', 'ai_generated_title')
    op.drop_column('app_ideas', 'ceo_feedback')
    op.drop_column('app_ideas', 'status')
    # Note: Autogenerate does not always create a command to drop the ENUM type.
    # This may need to be added manually if a full rollback is required.
    # op.execute("DROP TYPE ideastatus;")
    # ### end Alembic commands ###