"""Add competitor_data JSONB column to app_ideas

Revision ID: a8b2e4f19c03
Revises: f1c347d3dfad
Create Date: 2026-04-18 19:50:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8b2e4f19c03'
down_revision = 'f1c347d3dfad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_ideas', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('competitor_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_ideas', schema=None) as batch_op:
        batch_op.drop_column('competitor_data')
    # ### end Alembic commands ###
